[provider]
cluster = "devnet"
wallet = "/home/ilich/.config/solana/id.json"

[programs.devnet]
gaia_recs = "11111111111111111111111111111111"

[scripts]
test = "yarn run mocha -t 1000000 tests/**/*.ts"
lint = "cargo fmt --all && cargo clippy --all-targets --all-features -- -D warnings"
build = "anchor build"
deploy = "anchor deploy"
verify = "anchor verify"

[registry]
url = "https://anchor.projectserum.com"

[features]
seeds = false
skip-lint = false

[test]
skip-deploy = false
skip-local-validator = false
skip-build = false

[test.validator]
url = "https://api.devnet.solana.com"
commitment = "confirmed"
websocket = "wss://api.devnet.solana.com"
disable-blockhash-caching = false
preflight-commitment = "confirmed"
