[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
gaia_recs = "Cbi1bCczmVzuRc87YoGBhdiepZfiBkypM3J91PAp26YY"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/nicov/.config/solana/temp-keypair.json"

[scripts]
build = "anchor build"
deploy = "anchor deploy"
lint = "cargo fmt --all && cargo clippy --all-targets --all-features -- -D warnings"
test = "yarn run mocha -t 1000000 tests/**/*.ts"
verify = "anchor verify"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
bind_address = "0.0.0.0"
url = "https://api.devnet.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899
