[package]
name = "gaia_recs"
version = "0.1.0"
description = "Gaia RECs Solana Program"
edition = "2021"

[features]
no-entrypoint = []
no-idl = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = { version = "0.32.1", features = ["init-if-needed"] }
anchor-spl = "0.32.1"

[dev-dependencies]
anchor-lang = "0.32.1"

[lib]
crate-type = ["cdylib", "lib"]
name = "gaia_recs"
